language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t lothid/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true lothid/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-1-979052793209"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key: "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"