language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t lothid/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true lothid/docker-react npm run test